// <auto-generated />
using System;
using BookingTickets.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NewProjectMca.Migrations
{
    [DbContext(typeof(TicketDBContext))]
    [Migration("20250312062006_admin")]
    partial class admin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingTickets.Models.adminlogin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("admin_id"));

                    b.Property<string>("admin_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admin_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("admin_id");

                    b.ToTable("tbl_admin");
                });

            modelBuilder.Entity("BookingTickets.Models.booktrip", b =>
                {
                    b.Property<int>("b_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("b_id"));

                    b.Property<int?>("passengers")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("trip_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("trip_from")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trip_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("b_id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_booktrips");
                });

            modelBuilder.Entity("BookingTickets.Models.flight", b =>
                {
                    b.Property<int>("f_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_id"));

                    b.Property<DateTime?>("f_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("f_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_from")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("passengers")
                        .HasColumnType("int");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("f_id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_flight");
                });

            modelBuilder.Entity("BookingTickets.Models.user", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<string>("user_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("tbl_user");
                });

            modelBuilder.Entity("NewProjectMca.Models.bus", b =>
                {
                    b.Property<int>("b_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("b_id"));

                    b.Property<DateTime?>("b_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("b_from")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("b_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("passengers")
                        .HasColumnType("int");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("b_id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_bus");
                });

            modelBuilder.Entity("NewProjectMca.Models.contact", b =>
                {
                    b.Property<int>("c_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("c_id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("c_id");

                    b.ToTable("tbl_contact");
                });

            modelBuilder.Entity("NewProjectMca.Models.train", b =>
                {
                    b.Property<int>("t_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("t_id"));

                    b.Property<int?>("passengers")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("t_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("t_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t_from")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("t_id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_train");
                });

            modelBuilder.Entity("BookingTickets.Models.booktrip", b =>
                {
                    b.HasOne("BookingTickets.Models.user", "users")
                        .WithMany("Booktrips")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("BookingTickets.Models.flight", b =>
                {
                    b.HasOne("BookingTickets.Models.user", "users")
                        .WithMany("Flights")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("NewProjectMca.Models.bus", b =>
                {
                    b.HasOne("BookingTickets.Models.user", "users")
                        .WithMany("Buses")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("NewProjectMca.Models.train", b =>
                {
                    b.HasOne("BookingTickets.Models.user", "users")
                        .WithMany("Trains")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("BookingTickets.Models.user", b =>
                {
                    b.Navigation("Booktrips");

                    b.Navigation("Buses");

                    b.Navigation("Flights");

                    b.Navigation("Trains");
                });
#pragma warning restore 612, 618
        }
    }
}
